# Generated by Django 5.2.8 on 2025-11-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=150)),
                ('nome_popular', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='plantas/')),
                ('risco_extincao', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_bioma', models.CharField(default='Cerrado', max_length=100)),
                ('plantas', models.ManyToManyField(blank=True, related_name='regioes', to='catalogo_plantas.planta')),
            ],
        ),
        migrations.CreateModel(
            name='UsoMedicinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte_utilizada', models.CharField(max_length=100)),
                ('modo_preparo', models.CharField(max_length=200)),
                ('indicacao', models.CharField(max_length=200)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_medicinais', to='catalogo_plantas.planta')),
            ],
        ),
    ]
