# Generated by Django 5.2.8 on 2025-11-27 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_plantas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autores', models.CharField(max_length=255)),
                ('ano', models.PositiveIntegerField()),
                ('fonte', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes_cientificas', to='catalogo_plantas.planta')),
            ],
        ),
    ]
