# Generated by Django 5.2.8 on 2025-12-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_plantas', '0002_fontecientifica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiao',
            name='plantas',
        ),
        migrations.AddField(
            model_name='planta',
            name='regioes',
            field=models.ManyToManyField(blank=True, related_name='plantas', to='catalogo_plantas.regiao'),
        ),
    ]
